spring:
  config:
    import: "optional:configserver:http://localhost:8888"
  application:
    name: rnr-user-service
#
#
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    eureka-connection-idle-timeout-seconds: 60
#    service-url:
#      defaultZone: http://localhost:8761/eureka/

